run  "docker exec -i <container_name of database> <database> -u root --password= > initdb.sh"
###  Make a databse on phpmyadmin called guacamole. Then create a user called guacamole on that database with all perissions. Then on database permissions grant all except grant.###
version: '3'
services:
   guacd:
      container_name: guacd
      image: guacamole/guacd
      restart: unless-stopped
      hosrname: guacd
      volumes:
         - ~/docker/gcmle/guacd/data:/etc.guacamole
      ports:
         - 4822:4822
      networks:
         - guac
   guacamole:
      container_name: guacamole
      image: guacamole/guacamole
      restart: unless-stopped
      hostname: guacamole
      ports:
         - 9102:8080
      environment:
         GUACD_HOSTNAME: "guacd"
         GUACD_PORT: "4822"
         GUACAMOLE_HOME: "/etc/guacamole"
         MYSQL_HOSTNAME: ""
         MYSQL_PORT: "3306"
         MYSQL_DATABASE: "guacamole"
         MYSQL_USER: "guacamole"
         MYSQL_PASSWORD: ""
      depends_on:
         - guacd
      volumes:
         - ~/docker/gcmle/config:/etc/guacamole
      networks:
         - guac
      
networks:
   guac:
      external:
         name: guac
