version: '3.1'
services:
    db:
        image: mariadb:10.6
        container_name: maria 
        restart: unless-stopped
        volumes:
            - ~/docker/maria/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_USER=
            - MYSQL_PASSWORD=
            - MYSQL_DATABASE=mariadb
        ports:
            - "3306:3306"
        networks:
            - database
            
networks:
    database:
        driver: bridge
        external: true
