version: '3'
services:
    wordpress:
        image: wordpress:latest
        volumes: 
            - ~/docker/wrdps/data:/var/www/html
        ports:
            - 9107:80
        restart: unless-stopped
        environment:
            WORDPRESS_DB_HOST: 
            WORDPRESS_DB_USER: 
            WORDPRESS_DB_PASSWORD: 
            WORDPRESS_DB_NAME: 'wordpress'
            
##############Configured Database through PHPmyadmin with MariaDB 10.6##############
